[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "cenreg"
version = "0.1.0"
authors = [
  { name="Hiroki Yanagisawa", email="yanagisawa_hiroki@cyberagent.co.jp" },
]
description = "A Python library for censored regression."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "Apache License (2.0)"}
license-files = ["LICEN[CS]E*"]

dependencies = [
  "numpy",
  "scipy",
]

[dependency-groups]
dev = [
  "ty",
  "ruff",
  "pytest",
]
optional = [
  "pandas",
  "scikit-learn",
  "matplotlib",
]

[project.urls]
Homepage = "https://github.com/CyberAgentAILab/cenreg"
Issues = "https://github.com/CyberAgentAILab/cenreg/issues"
